version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: sh -c "npm run migrate up && npm run dev"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./docs:/app/docs

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
